from percorrendo_arquivo import percorrendo_arquivo
from percorrendo_json import percorrendo_json
from percorrendo_lista import percorre_lista_precos, percorre_lista_produtos
from percorrendo_range import percorrendo_range

percorrendo_arquivo()
